# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-09 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181009_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
